### ISSUE TITLE
Starter Content

### ISSUE THREAD

**Issue by NomeQ** [Trillium-Solutions/transit-base-template#7]
Add option to initialize with starter content, determine essential content. 

- Pages: About, Contact, How to Ride, Fares and Passes, Routes, Title VI

**Comment by sleddd** [comment]
@NomeQ @ekeaton While I was not really able to determine essential content, I did create a starter content and page/post generator function to help with generating the Cape Anne pages. If you pass in use_defaults as true, then it will generate the default pages you mentioned above @NomeQ.  However, if you pass in a custom set of post objects, then it will generate the pages from those instead. You don't have to pass in anything except post title for it to work: 

Example using some of the CATA pages: 
$args = array(
	array(
		'post_title' => 'Dial A Ride'
	), 
	array(
		'post_title' => 'About Us'
	), 
	array(
		'post_title' => 'Employment'
	), 
	array(
		'post_title' => 'Open Government'
	), 
);
transit_base_template_create_pages( $args );

If the page already exists, then it won't recreate them.  Also, you must be logged in as an admin and on admin side for it to run. Full documentation is available in the template tag function itself: 

transit_base_template_create_pages( $args = array(), $use_defaults = false );

Closing this issue now.
